import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/Navbar";
import ToastrProvider from "./providers/ToastrProvider";



export const metadata: Metadata = {
  title: "Carsties",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastrProvider/>      
        <Navbar />
        <main className="container mx-auto px-5 pt-10">
        {children}
        </main>     
      </body>
    </html>
  );
}
